### ISSUE TITLE
Support 3 legged auth 

### ISSUE THREAD

**Issue by Band-Aid** [box/boxcli#107] opened 2018-10-19 01:38 UTC
Currently Box CLI only supports JWT Auth but I would like this to support 3 legged auth so that end users can use Box CLI against their own folders.

**Comment by mattwiller** [comment] 2018-10-19 22:03
I'm going to close this since it's a duplicate of #79 — @Band-Aid could you please head over to that issue and let me know what sort of use case you envision for this functionality?

**Closed by mattwiller** 2018-10-19 22:03 UTC
